# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'to-do-list' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for to-do-list

  target 'to-do-listTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'to-do-listUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'SwiftLint'


end
